# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "packages/components/" 
    versioning-strategy: increase
    schedule:
      interval: "weekly"
    allow: 
      - dependency-name: "@percy/*"
  - package-ecosystem: "npm" 
    directory: "packages/ember-flight-icons/" 
    versioning-strategy: increase
    schedule:
      interval: "weekly"
    allow: 
      - dependency-name: "@percy/*"
  - package-ecosystem: "npm" 
    directory: "flight-website/" 
    versioning-strategy: increase
    schedule:
      interval: "weekly"
    allow: 
      - dependency-name: "@percy/*"

