# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "packages/components/" 
    versioning-strategy: increase
    schedule:
      interval: "weekly"
    allow: 
      - dependency-name: "@percy/*"
    ignore:
      # For Percy, ignore all patch updates
      - dependency-name: "@percy/*"
        update-types: ["version-update:semver-patch"]
