name: CI - Components - Nightly
    
on:
  # schedule:
    # Runs at 00:00 UTC
    # - cron:  '0 0 * * *'
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'

concurrency:
   group: ci-components-nightly-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  test:
    name: "A11y Nightly Tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Create directory for test results if one does not already exist
        working-directory: packages/components
        run: mkdir -p ember-a11y-report

      - name: Run Tests
        run: yarn run test:a11y-report
        working-directory: packages/components
        continue-on-error: true
      
      - name: Archive a11y test results
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: a11y-test-results
          path: packages/components/ember-a11y-report/*.json
          

