name: CI - Ember Flight Icons
    
on:
  push:
    branches:
      - main
  pull_request: {}

env:
  NODE_VERSION: '16.x'

concurrency:
   group: ci-ember-flight-icons-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Lint
        run: yarn run lint
        working-directory: packages/ember-flight-icons
