name: Update Search Index
    
on:
  workflow_dispatch:
#  push:
  # branches:
  #   - main

env:
  NODE_VERSION: '20.x'

jobs:
  update_index:
    name: Update Search Index
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Install Node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
          cache-dependency-path: yarn.lock
          
      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build website
        run: yarn workspace website build

      - name: Update Search Index
        run: yarn workspace website algolia:index
        env:
          ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          ALGOLIA_API_KEY_ADMIN: ${{ secrets.ALGOLIA_API_KEY_ADMIN }}
          ALGOLIA_INDEX_ID: ${{ secrets.ALGOLIA_INDEX_ID }}
